### ISSUE TITLE
Return all log lines by default -> from_ms=0?

### ISSUE THREAD

**Issue by kodemaniak** [logtopus/tentacle#8]
Does it make sense to use 0 as default `from_ms` timestamp insteady of `SystemTime::now()`.

**Comment by niveau0** [comment]
I think the default should reflect what most people want to see in logs by, erm, default.
What use cases exist? 
monitoring, statistics,debugging, find errors what else?

**Comment by niveau0** [comment]
Decision: API should not try to be intelligent, default is 0, client should decide
